---
title: "Qualities of Volunteering and Life Satisfaction: A multiple linear regression model"
subtitle: "Insights from the 2018 Canadian General Social Survey"
author: Kimlin Chin
thanks: "Code and data are available at: https://github.com/KCtt457/gssvolunteering2018."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Volunteering has been linked to many benefits including health, happiness and life satisfaction; however, there is limited research on the precise aspects of volunteering associated with these benefits. In this paper, we investigate how different aspects of volunteering including frequency, reasons and quality of experience in volunteering are correlated with life satisfaction using a multiple linear regression model. We find that among people who volunteer, people who use their skills in their volunteering experience and volunteer at least once a week had higher life satisfaction. Our findings have implications for the general public in making the most out of their volunteer experience. \\par \\textbf{Keywords:} volunteering, life satisfaction, multiple linear regression, canadian general social survey, canada"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

gss1 <- read_csv(here::here("inputs/data/gss.csv"))
```

# Introduction

<!-- Background, context -->
Volunteering has been linked to many benefits including health, happiness and life satisfaction (cite literature).

But what specific aspects of volunteering may be related to life satisfaction? In this paper we take a look at the data from the 2018 Canadian General Social Survey on Giving, Volunteering & Participating to investigate this question. Specifically we construct a multiple linear regression model with life satisfaction as our dependent variable, and independent variables for frequency, reasons for volunteering and quality of volunteer experience. We find that among people who volunteer, people who use their skills in their volunteering experience and volunteer at least once a week had higher life satisfaction.

The rest of the paper has the following structure: Section \@ref(data) describes the data from the 2018 Canadian General Social Survey on Giving, Volunteering & Participating, Section \@ref(model) discusses the multiple linear regression model, Section \@ref(results) presents the results of our analysis and Section \@ref(discussion) discusses the findings and limitations.

# Data

The data is from the 2018 Canadian General Social Survey on Giving, Volunteering & Participating. There are 956 variables and 16,149 observations in the dataset.

The variables include basic demographic information, such as age, gender, marital status, province, as well as depict the topics of volunteer specifics and details, reasons for volunteering or not volunteering, quality and history of volunteering, financial giving and youth experiences.

A subset of the variables is shown in table 1.

`R` [@citeR] and the R package `tidyverse` which was written by @thereferencecanbewhatever were used for data processing and to make the plots and tables.


# Model

\begin{equation}
Pr(\theta | y) = \frac{Pr(y | \theta) Pr(\theta)}{Pr(y)}  (\#eq:bayes)
\end{equation}

Equation \@ref(eq:bayes) seems useful, eh?

Here's a dumb example of how to use some references: In paper we run our analysis in `R` [@citeR]. We also use the `tidyverse` which was written by @thereferencecanbewhatever If we were interested in baseball data then @citeLahman could be useful. 

We can use maths by including latex between dollar signs, for instance $\theta$.


# Results

# Discussion

## First discussion point

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional details


\newpage


# References


